### PR TITLE
Capstone Project

### PR DESCRIPTION
**Pull request by lorenzoworx**
## Learning Objectives
- Use semantic HTML tags.
- Apply HTML best practices.
- Use CSS box model.
- Use Flexbox to layout page.
- Demonstrate ability to create UIs adaptable to different screen sizes using media queries.
- Use GitHub Pages to deploy web pages.
- Apply JavaScript best practices and language style guides in code.
- Use JavaScript to manipulate DOM elements.
- Use JavaScript events.
- Use objects to store and access data.
- Communicate technical concepts to other technical people.

### CODE REVIEW

**Review by Olamarx — CHANGES_REQUESTED** [review]
Hi @lorenzoworx, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- Linters passed ✔️ 
- Commit messages ✔️ 
- PR description ✔️ 

## Required Changes ♻️
_Check the comments under the review._
### Most of the changes are merged so I made general comments
- [x] You have probably forgotten to record the video. The video is essential because it helps the reviewer to know what you built and what interests you.
- [x] You also forgot the Acknowledgement of the designer of the page. Kindly acknowledge the designer as it is a requirement to use the design.
- [x] The mobile version of the home page does not show the hamburger unless i increase the size to ipad size which should not be. I feel the media styling is the issue here as I can see the content of the page is also shifted to the top.
### Your design
image

### Behance 
image

- [x]  Kindly properly align the aspect I circled in the image below so that it would align as it is on Behance

### Your work
image
### Behance
image
- [x] Kindly center the content I circled so that it would look like the Behance design

### Your design
image

### Behance Design
image

- [x] Kindly center the one I circled in green and kindly adjust the logo from the line(the one I circled in yellow)

### Your work
image

### Behance
image

- [x] Kindly give the proper space to the footer content to look like the Behance

### your work
image

### Behance
image
- [x] I can see you used many h1 tags, for semaqntic reasons, only one h1 tag should be used on a webpage because h1 tag carries a title message and there cant be two titles in a page. As a result, I would recommend you change other h1 and leave the one you would like to carry the title header. You can use other hx for others.
- [x] For the speakers, nice one putting it in an array but I would recommend you iterate over it in a function so that separation of concerns can be fulfilled. I mean each functions can carry out their duty when called and not leave a code to just run at every lauch of the page. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lorenzoworx** [comment]
Hello @Olamarx, next time, you should leave inline comments so I can interact with them individually. I don't understand what you're asking in the last comment about javascript. Can you please clarify this for me? I've sent you a message on slack already.

**Comment by Olamarx** [comment]
I would have left inline comment but you have merged all the changes.

All I am saying is that you should put the code in a function and just call it.

**Review by brainconnect93 — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi @lorenzoworx , 👋 

Your project is complete! Great job for following the project requirement🥇and implementing the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 




## Good Points 👍

- Has a proper Pull Request. ✔️
- No Linter errors ✔️
- Good use of Github flow ✔️

## Optional changes

- [x] Great effort working on your project and also implementing the changes requested by the previous reviewer. I would kindly suggest you add the link to the Cindy Shin design in the Acknowledgment part of your READE file. I can see you only mention the name (Cindy Shin) but you haven't given visitors the link to the original design for their peruse.
  -Thank You.


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
